//----------------------------------------------------------------------------------
// <autogenerated>
//		This code was generated by a tool.
//		Changes to this file may cause incorrect behaviour and will be lost 
//		if the code is regenerated.
// </autogenerated>
//----------------------------------------------------------------------------------

using System;
using System.Text;
using System.Collections;
using System.ComponentModel;
using System.Globalization;
using Soneta.Types;
using Soneta.Business;
using BPX_NSA;
using BPX_NSA;

[assembly: ModuleType("BPX_NSA", typeof(BPX_NSA.BPX_NSAModule), 4, "BPX_NSA_1", 0, VersionNumber=1)]

namespace BPX_NSA;

/// <summary>
/// Moduł BPX_NSA.
/// <seealso cref="BPX_NSA"/>
/// </summary>
/// <seealso cref="Soneta.Business.Module"/>
/// <seealso cref="Soneta.Business.Session"/>
[System.CodeDom.Compiler.GeneratedCode("Soneta.CodeGenerators", "4")]
public partial class BPX_NSAModule : Module {

    public static BPX_NSAModule GetInstance(ISessionable session) => (BPX_NSAModule)session?.Session?.Modules[moduleInfo];

    private static Soneta.Business.App.ModuleInfo moduleInfo = new(session => new BPX_NSAModule(session)) {
    };

    private BPX_NSAModule(Session session) : base(session) {}

    private BPX_NSAModule moduleBPX_NSA;

    [Browsable(false)]
    public BPX_NSAModule BPX_NSA => moduleBPX_NSA ??= BPX_NSAModule.GetInstance(Session);

}

[System.CodeDom.Compiler.GeneratedCode("Soneta.CodeGenerators", "4")]
public static class StaticsBPX_NSAModule {
    public static BPX_NSAModule GetBPX_NSA(this Session session) => BPX_NSAModule.GetInstance(session);
}

