//----------------------------------------------------------------------------------
// <autogenerated>
//		This code was generated by a tool.
//		Changes to this file may cause incorrect behaviour and will be lost 
//		if the code is regenerated.
// </autogenerated>
//----------------------------------------------------------------------------------

using System;
using System.Text;
using System.Collections;
using System.ComponentModel;
using System.Globalization;
using Soneta.Types;
using Soneta.Business;
using InSolutions_NSA;
using InSolutions_NSA;

[assembly: ModuleType("InSolutions_NSA", typeof(InSolutions_NSA.InSolutions_NSAModule), 4, "InSolutions_NSA_1", 0, VersionNumber=1)]

namespace InSolutions_NSA;

/// <summary>
/// Moduł InSolutions_NSA.
/// <seealso cref="InSolutions_NSA"/>
/// </summary>
/// <seealso cref="Soneta.Business.Module"/>
/// <seealso cref="Soneta.Business.Session"/>
[System.CodeDom.Compiler.GeneratedCode("Soneta.CodeGenerators", "4")]
#warning Description for module 'InSolutions_NSA' is not defined
public partial class InSolutions_NSAModule : Module {

    public static InSolutions_NSAModule GetInstance(ISessionable session) => (InSolutions_NSAModule)session?.Session?.Modules[moduleInfo];

    private static Soneta.Business.App.ModuleInfo moduleInfo = new(session => new InSolutions_NSAModule(session)) {
    };

    private InSolutions_NSAModule(Session session) : base(session) {}

    private InSolutions_NSAModule moduleInSolutions_NSA;

    [Browsable(false)]
    public InSolutions_NSAModule InSolutions_NSA => moduleInSolutions_NSA ??= InSolutions_NSAModule.GetInstance(Session);

}

[System.CodeDom.Compiler.GeneratedCode("Soneta.CodeGenerators", "4")]
public static class StaticsInSolutions_NSAModule {
    public static InSolutions_NSAModule GetInSolutions_NSA(this Session session) => InSolutions_NSAModule.GetInstance(session);
}

