//----------------------------------------------------------------------------------
// <autogenerated>
//		This code was generated by a tool.
//		Changes to this file may cause incorrect behaviour and will be lost 
//		if the code is regenerated.
// </autogenerated>
//----------------------------------------------------------------------------------

using System;
using System.Text;
using System.Collections;
using System.ComponentModel;
using System.Globalization;
using Soneta.Types;
using Soneta.Business;
using DRIT_NSA;
using DRIT_NSA;

[assembly: ModuleType("DRIT_NSA", typeof(DRIT_NSA.DRIT_NSAModule), 4, "DRIT_NSA_1", 0, VersionNumber=1)]

namespace DRIT_NSA;

/// <summary>
/// Moduł DRIT_NSA.
/// <seealso cref="DRIT_NSA"/>
/// </summary>
/// <seealso cref="Soneta.Business.Module"/>
/// <seealso cref="Soneta.Business.Session"/>
[System.CodeDom.Compiler.GeneratedCode("Soneta.CodeGenerators", "4")]
#warning Description for module 'DRIT_NSA' is not defined
public partial class DRIT_NSAModule : Module {

    public static DRIT_NSAModule GetInstance(ISessionable session) => (DRIT_NSAModule)session?.Session?.Modules[moduleInfo];

    private static Soneta.Business.App.ModuleInfo moduleInfo = new(session => new DRIT_NSAModule(session)) {
    };

    private DRIT_NSAModule(Session session) : base(session) {}

    private DRIT_NSAModule moduleDRIT_NSA;

    [Browsable(false)]
    public DRIT_NSAModule DRIT_NSA => moduleDRIT_NSA ??= DRIT_NSAModule.GetInstance(Session);

}

[System.CodeDom.Compiler.GeneratedCode("Soneta.CodeGenerators", "4")]
public static class StaticsDRIT_NSAModule {
    public static DRIT_NSAModule GetDRIT_NSA(this Session session) => DRIT_NSAModule.GetInstance(session);
}

